---
name: Luis
surname: de Sousa
position: "Data and Analytics Consultant"
#pronouns: he/him
address: "Johannesburg, South Africa"
#www: www.growinconsultation.com
email: "luisd@syeop.co.za"
twitter: luis_de_sousa
github: luisdza
linkedin: luisdza
date: "`r format(Sys.time(), '%B %Y')`"
docname: "Cover Letter"
output:
  vitae::awesomecv:
    page_total: true
#profilepic: luisdza-headshot.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

[Date]  

[Recipient Name]  
[Company Name]  
[Company Address]  
[City, State, Zip Code]  

Dear [Recipient Name],

I am writing to express my interest in the [specific position] at [Company Name]. With over 16 years of robust experience in data and analytics consulting, I have honed a skill set that perfectly aligns with the demands of this role, especially in designing and deploying sophisticated data solutions for large organizations. My tenure as Principal Consultant and Director at Syeop in Johannesburg has equipped me with the expertise to drive significant projects from conception through to execution, ensuring both technical and business objectives are met seamlessly.

At Syeop, I lead diverse and high-impact initiatives across sectors like real estate, food and beverage, and banking, demonstrating my ability to adapt and innovate across various market demands. My role involves strategic business management, from prospecting and negotiation to overseeing comprehensive project and team management. Technically, I am adept with a broad suite of technologies, including Microsoft Data Platform, MySQL, Google BigQuery, Azure Databricks, and FiveTran, and I am proficient in SQL, R, and Python. This blend of management and technical skills ensures I am well-prepared to contribute effectively to your team.

I am particularly drawn to [Company Name] due to [mention any specific reason related to the company's projects, values, or reputation in the industry]. I am enthusiastic about the opportunity to bring my unique expertise in data warehousing, integration, and analytics to your company, contributing to innovative solutions that enhance data-driven decision-making.

Beyond my professional endeavours, I am involved in the data science community as a co-organizer of the Johannesburg R User Group and the PyData Johannesburg chapter. These roles underscore my commitment to fostering a collaborative professional community and staying at the forefront of technological advancements in data analytics.

I look forward to discussing how my background, skills, and enthusiasm align with the goals of [Company Name]. I am available at your earliest convenience for a discussion and can be reached via email at [your email] or by phone at [your phone number]. Thank you for considering my application. I am eager to contribute to your esteemed team potentially and am excited about the direction [Company Name] is headed.

Regards,

Luis de Sousa
