# Name of the workflow
name: CI

# Events that trigger the workflow
on:
  # Trigger the workflow on push or pull request
  # events but only for the main branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Also allows running the workflow manually from the GitHub Actions UI
  workflow_dispatch:

# Permissions for the workflow
permissions:
  # Allows the workflow to write to the repository
  contents: write

# Define jobs
jobs:
  # Job for building the CV
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Setup Pandoc
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      # Setup R
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          # Use public RSPM
          use-public-rspm: true

      # Install R Dependencies
      - name: Install R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      # Install Tinytex
      - name: Install Tinytex
        run: tinytex::install_tinytex()
        shell: Rscript {0}

      # Knit CV R Markdown to PDF
      - name: Knit CV R Markdown to PDF
        run: rmarkdown::render("cv.Rmd")
        shell: Rscript {0}

      # Knit Resume R Markdown to PDF
      - name: Knit Resume R Markdown to PDF
        run: rmarkdown::render("resume.Rmd")
        shell: Rscript {0}

      # Knit Resume R Markdown to PDF
      - name: Knit Cover letter R Markdown to PDF
        run: rmarkdown::render("cover-letter.Rmd")
        shell: Rscript {0}

      # Upload PDF
      - name: Upload PDF
        run: |
          # Configure git user
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          # Add generated PDFs to git
          git add *.pdf
          # Commit the changes
          git commit -am "add the generated pdfs to the repository"
          # Push the changes
          git push
